### PR TITLE
Updating to Hydro with turtlesim twist messages

### PR DESCRIPTION
**Pull request by trygveu**
Turtlesim has been changed in Hydro to use geometry_msgs/Twist in stead of the old Velocity message. The tutorial wiki and this source code should be updated to reflect this.

### CODE REVIEW

**Comment by trygveu** [comment]
I tried to squash this, but just ended up making it worse and added two bogus commits when I did 'git push -f`. I'd gladly take some tips on how to fix this.

**Comment by zchen24** [comment]
@trygveu Maybe create a new branch (let's call it fix). Switch back to master, reset master HEAD to bfe4aa5 (fuerte release). Then rebase from your fix branch. After rebase, you can git push -f

**Comment by zchen24** [comment]
@jbohren Is this package still maintained? It's used here http://wiki.ros.org/action/login/joy/Tutorials/WritingTeleopNode

**Comment by trygveu** [comment]
Hi @zchen24, I'll have a look at this tonight and fix a proper merge request. Thanks for looking into it.

**Pull request closed without merging**
